In [55]:
#importing libraries
import numpy as np
# cv2 save in bgr format
import cv2
#plt save in rgb format
import matplotlib.pyplot as plt

In [56]:
img = cv2.imread('/home/user/project/images/car.jpeg')
print(img)
#(row column channel) red channel, green channel, blue channel etc

[[[133 154 169]
  [132 153 168]
  [132 153 168]
  ...
  [123 142 155]
  [123 142 155]
  [122 141 156]]

 [[116 137 152]
  [116 137 152]
  [115 136 151]
  ...
  [102 121 134]
  [103 122 135]
  [105 124 139]]

 [[122 143 158]
  [123 144 159]
  [124 145 160]
  ...
  [100 122 134]
  [ 99 121 133]
  [ 99 121 133]]

 ...

 [[126 150 168]
  [116 140 158]
  [ 87 111 129]
  ...
  [123 144 159]
  [141 160 175]
  [141 157 173]]

 [[ 97 121 139]
  [ 93 117 135]
  [ 73  97 115]
  ...
  [105 128 143]
  [140 161 176]
  [159 174 190]]

 [[ 67  91 111]
  [ 78 102 122]
  [ 96 120 138]
  ...
  [ 89 117 128]
  [107 133 145]
  [119 141 153]]]


In [57]:
img.min()

0

In [58]:
img.max()

255

In [59]:
img.shape

(683, 1217, 3)

In [60]:
img = plt.imread('/home/user/project/images/car.jpeg')
print(img)

[[[169 154 133]
  [168 153 132]
  [168 153 132]
  ...
  [155 142 125]
  [155 142 125]
  [156 141 122]]

 [[152 137 116]
  [152 137 116]
  [151 136 115]
  ...
  [134 121 102]
  [135 122 103]
  [139 124 105]]

 [[158 143 122]
  [159 144 123]
  [160 145 124]
  ...
  [134 122 100]
  [133 121  99]
  [133 120 101]]

 ...

 [[168 150 126]
  [158 140 116]
  [129 111  87]
  ...
  [159 144 123]
  [175 160 139]
  [173 157 142]]

 [[139 121  97]
  [135 117  93]
  [115  97  73]
  ...
  [143 129 103]
  [176 161 138]
  [190 173 163]]

 [[111  91  67]
  [120 102  78]
  [138 120  96]
  ...
  [130 116  89]
  [145 134 106]
  [153 140 123]]]


In [61]:
img.min()

0

In [62]:
img.max()

255

In [63]:
img.shape

(683, 1217, 3)